import { count } from "drizzle-orm";
import type { PostgresJsDatabase } from "drizzle-orm/postgres-js";
import * as schema from "@/db/schema";
import {
  cannedResponses,
  kbArticles,
  roadmapItems,
} from "@/db/schema";

type AppDb = PostgresJsDatabase<typeof schema>;

export const CRM_DDL = `
CREATE TABLE IF NOT EXISTS agents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'agent',
  password_hash TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'online',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS contacts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  app_user_id UUID UNIQUE,
  email TEXT,
  name TEXT,
  license_tier TEXT,
  subscription_status TEXT,
  phone TEXT,
  tags TEXT[] NOT NULL DEFAULT '{}',
  last_seen_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  number INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) UNIQUE NOT NULL,
  contact_id UUID REFERENCES contacts(id) ON DELETE SET NULL,
  assignee_id UUID REFERENCES agents(id) ON DELETE SET NULL,
  subject TEXT NOT NULL,
  description TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open',
  priority TEXT NOT NULL DEFAULT 'medium',
  type TEXT NOT NULL DEFAULT 'general',
  source TEXT NOT NULL DEFAULT 'app',
  tags TEXT[] NOT NULL DEFAULT '{}',
  app_feedback_id UUID UNIQUE,
  first_response_at TIMESTAMPTZ,
  resolved_at TIMESTAMPTZ,
  csat_score INTEGER,
  csat_comment TEXT,
  first_response_due_at TIMESTAMPTZ,
  resolution_due_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ticket_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id UUID NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  author_type TEXT NOT NULL,
  author_id UUID,
  author_name TEXT NOT NULL,
  body TEXT NOT NULL,
  is_internal BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS canned_responses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  shortcut TEXT UNIQUE,
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS kb_articles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  category TEXT NOT NULL DEFAULT 'General',
  body TEXT NOT NULL,
  published BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS roadmap_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  body TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'considering',
  published BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  vote_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS roadmap_votes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  item_id UUID NOT NULL REFERENCES roadmap_items(id) ON DELETE CASCADE,
  voter_key TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (item_id, voter_key)
);

CREATE INDEX IF NOT EXISTS roadmap_items_status_sort_idx ON roadmap_items (status, sort_order);
CREATE INDEX IF NOT EXISTS roadmap_votes_item_idx ON roadmap_votes (item_id);

CREATE TABLE IF NOT EXISTS sla_policies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  is_default BOOLEAN NOT NULL DEFAULT TRUE,
  first_response_hours TEXT NOT NULL,
  resolve_hours TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS automation_rules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  trigger TEXT NOT NULL,
  conditions TEXT NOT NULL DEFAULT '[]',
  actions TEXT NOT NULL DEFAULT '[]',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS automation_rules_trigger_idx ON automation_rules (trigger, enabled);
`;

async function seedCannedResponses(database: AppDb) {
  await database.insert(cannedResponses).values([
    {
      title: "Thanks, looking into it",
      shortcut: "#thanks",
      body: "Thank you for the report — we have this in the reader queue and will update you as soon as we reproduce it.",
    },
    {
      title: "License / devices",
      shortcut: "#devices",
      body: "A Full license is per person. Churches typically assign one Full seat per teacher.",
    },
    {
      title: "Billing received",
      shortcut: "#billing",
      body: "I see the Stripe event on our side. I am reviewing the invoice now and will confirm refund or credit shortly.",
    },
  ]);
}

async function seedKbArticles(database: AppDb) {
  await database.insert(kbArticles).values([
    {
      title: "Contact Discovery Bible support",
      slug: "contact-support",
      category: "Getting started",
      body: "From the reader, open Help → Send feedback. In-app feedback becomes a CRM ticket automatically.",
    },
    {
      title: "Device limits on a Full license",
      slug: "device-limits",
      category: "Billing",
      body: "Full licenses allow a small set of devices per person. Sharing one login across a church staff is not supported.",
    },
  ]);
}

async function seedRoadmapItems(database: AppDb) {
  await database.insert(roadmapItems).values([
    {
      title: "Offline chapter download",
      body: "Download a book or chapter for reading without a network connection.",
      status: "in_progress",
      published: true,
      sortOrder: 10,
      voteCount: 42,
    },
    {
      title: "Shared church reading plans",
      body: "Pastors assign a plan; members see progress together.",
      status: "planned",
      published: true,
      sortOrder: 10,
      voteCount: 28,
    },
    {
      title: "Dark mode for the reader",
      body: "System-aware and manual dark theme across reading and study panes.",
      status: "shipped",
      published: true,
      sortOrder: 10,
      voteCount: 61,
    },
    {
      title: "Audio Bible playback",
      body: "Listen while following along in the text, with verse sync.",
      status: "considering",
      published: true,
      sortOrder: 10,
      voteCount: 55,
    },
    {
      title: "Export highlights to PDF",
      body: "Export selected notes and highlights as a printable PDF.",
      status: "considering",
      published: true,
      sortOrder: 20,
      voteCount: 19,
    },
    {
      title: "Multi-column parallel layout on desktop",
      body: "Compare three translations side by side on wide screens.",
      status: "planned",
      published: true,
      sortOrder: 20,
      voteCount: 33,
    },
  ]);
}

/** Create CRM tables. Staff agents are created from NextAuth on first visit. */
export async function bootstrapDb(database: AppDb) {
  const [cannedCount] = await database.select({ n: count() }).from(cannedResponses)
  if ((cannedCount?.n ?? 0) === 0) {
    await seedCannedResponses(database)
  }
  const [kbCount] = await database.select({ n: count() }).from(kbArticles)
  if ((kbCount?.n ?? 0) === 0) {
    await seedKbArticles(database)
  }
  const [roadmapCount] = await database.select({ n: count() }).from(roadmapItems)
  if ((roadmapCount?.n ?? 0) === 0) {
    await seedRoadmapItems(database)
  }
}

/** @deprecated Use bootstrapDb */
export const bootstrapLocalDb = bootstrapDb;
