import { count } from "drizzle-orm";
import type { PostgresJsDatabase } from "drizzle-orm/postgres-js";
import * as schema from "@/db/schema";
import {
  cannedResponses,
  kbArticles,
} from "@/db/schema";

type AppDb = PostgresJsDatabase<typeof schema>;

export const CRM_DDL = `
CREATE TABLE IF NOT EXISTS agents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'agent',
  password_hash TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'online',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS contacts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  app_user_id UUID UNIQUE,
  email TEXT,
  name TEXT,
  license_tier TEXT,
  subscription_status TEXT,
  phone TEXT,
  tags TEXT[] NOT NULL DEFAULT '{}',
  last_seen_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  number INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) UNIQUE NOT NULL,
  contact_id UUID REFERENCES contacts(id) ON DELETE SET NULL,
  assignee_id UUID REFERENCES agents(id) ON DELETE SET NULL,
  subject TEXT NOT NULL,
  description TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open',
  priority TEXT NOT NULL DEFAULT 'medium',
  type TEXT NOT NULL DEFAULT 'general',
  source TEXT NOT NULL DEFAULT 'app',
  tags TEXT[] NOT NULL DEFAULT '{}',
  app_feedback_id UUID UNIQUE,
  first_response_at TIMESTAMPTZ,
  resolved_at TIMESTAMPTZ,
  csat_score INTEGER,
  csat_comment TEXT,
  first_response_due_at TIMESTAMPTZ,
  resolution_due_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ticket_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id UUID NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  author_type TEXT NOT NULL,
  author_id UUID,
  author_name TEXT NOT NULL,
  body TEXT NOT NULL,
  is_internal BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS canned_responses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  shortcut TEXT UNIQUE,
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS kb_articles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  category TEXT NOT NULL DEFAULT 'General',
  body TEXT NOT NULL,
  published BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS roadmap_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  body TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'considering',
  published BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  vote_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS roadmap_votes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  item_id UUID NOT NULL REFERENCES roadmap_items(id) ON DELETE CASCADE,
  voter_key TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (item_id, voter_key)
);

CREATE INDEX IF NOT EXISTS roadmap_items_status_sort_idx ON roadmap_items (status, sort_order);
CREATE INDEX IF NOT EXISTS roadmap_votes_item_idx ON roadmap_votes (item_id);

CREATE TABLE IF NOT EXISTS sla_policies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  is_default BOOLEAN NOT NULL DEFAULT TRUE,
  first_response_hours TEXT NOT NULL,
  resolve_hours TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS automation_rules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  trigger TEXT NOT NULL,
  conditions TEXT NOT NULL DEFAULT '[]',
  actions TEXT NOT NULL DEFAULT '[]',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS automation_rules_trigger_idx ON automation_rules (trigger, enabled);
`;

async function seedCannedResponses(database: AppDb) {
  await database.insert(cannedResponses).values([
    {
      title: "Thanks, looking into it",
      shortcut: "#thanks",
      body: "Thank you for writing in. We have your request and will follow up shortly.",
    },
    {
      title: "Need a bit more detail",
      shortcut: "#details",
      body: "Could you share a bit more context so we can help accurately? Screenshots or the page URL are useful if you have them.",
    },
    {
      title: "Resolved — closing out",
      shortcut: "#resolved",
      body: "Glad this is sorted. I am marking the ticket resolved. Reply on this thread if anything else comes up.",
    },
  ]);
}

async function seedKbArticles(database: AppDb) {
  await database.insert(kbArticles).values([
    {
      title: "Contact ScioLabs support",
      slug: "contact-support",
      category: "Getting started",
      body: "Open a ticket at /support/tickets/new or submit a form on the website. We reply by email and in this portal.",
    },
    {
      title: "Track an existing request",
      slug: "track-ticket",
      category: "Getting started",
      body: "Sign in to the support portal with the email you used on the form. Your tickets appear under My tickets.",
    },
  ]);
}

/** Create CRM tables. Staff agents are created from NextAuth on first visit. */
export async function bootstrapDb(database: AppDb) {
  const [cannedCount] = await database.select({ n: count() }).from(cannedResponses)
  if ((cannedCount?.n ?? 0) === 0) {
    await seedCannedResponses(database)
  }
  const [kbCount] = await database.select({ n: count() }).from(kbArticles)
  if ((kbCount?.n ?? 0) === 0) {
    await seedKbArticles(database)
  }
}

/** @deprecated Use bootstrapDb */
export const bootstrapLocalDb = bootstrapDb;
